### ISSUE TITLE
Don't burn CPU in the menu

### ISSUE THREAD

**Issue by dennwc** [noxworld-dev/opennox#237]
Currently Nox wastes time of a single CPU core when staying idle in the menu.

**Comment by angrykirc** [comment]
Seemingly this is fixed now in around 295a47180deeb2b0d5a2b7cd8bb11362378941a7
I feel sorry tbh...
Tested on Linux, waiting for someone to confirm on Windows

**Comment by dennwc** [comment]
I initially reported this for Linux, and also haven't noticed high CPU usage recently. So I think we can close it.
