### ISSUE TITLE
Lightning spell or energy bolt spell can attack monsters out of sight.

### ISSUE THREAD

**Issue by hjyoon** [noxworld-dev/opennox#374]
This is possible if it is obscured by a specific structure rather than a wall.

![image](https://user-images.githubusercontent.com/16138767/136832082-ab2c8947-1802-4ca8-9117-3b56228207fd.png)

**Comment by dennwc** [comment]
It also affects the recently ported Death Ray spell, the [ray tracing routine](https://github.com/noxworld-dev/opennox/blob/cbabc5a6f2fcb0f846b993f0a16a2d33335531b0/src/spell_death_ray.go#L29) gives incorrect results. I briefly checked the ray tracing, can't find any obvious failure.

The cause could be related to how the size of these blocks is calculated and/or how the data structure for ray tracing is updated based on these moving blocks.

**Comment by KILAH4716** [comment]
As dennwc and I have discussed through a video, this is not just a Wizard issue. I bet the Conjurer can cast behind the cinderblocks, and enemy entities can see behind the blocks.

**Comment by dennwc** [comment]
Now that the #307 is fixed, I think we'll need to check this one as well. It seems like it could be using the same function under the hood.

**Comment by dennwc** [comment]
Looks like it's fixed too :tada: Cannot reproduce anymore.
